[package]
name = "granne-py"
version = "0.5.2"
authors = ["Erik Larsson <erik@cliqz.com>"]
edition = "2018"

[lib]
name = "granne"
crate-type = ["cdylib"]

[features]
blas = ["granne/blas"]

[dependencies]
granne = { path = ".." }
rayon = "1.3"
serde_json = "1.0"
cpython = {version = "0.6"}
